py.test --alluredir allure-results test\test_add_contact.py
py.test --alluredir allure-results test\test_del_contact.py
py.test --alluredir allure-results test\test_update_contact.py
py.test --alluredir allure-results test\test_add_group.py
py.test --alluredir allure-results test\test_del_group.py
py.test --alluredir allure-results test\test_modify_group.py
py.test --alluredir allure-results test\test_add_contact_into_group.py
py.test --alluredir allure-results test\test_delete_contact_from_group.py
py.test --alluredir allure-results test\test_homepage_data.py
C:\Allure\allure-commandline-2.13.8\allure-2.13.8\bin\allure.bat generate allure-results --clean